name: natacaoapp
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.1.1 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^2.21.0
  firebase_auth: ^4.12.1
  cloud_firestore: ^4.13.3
  firebase_messaging: ^14.7.3
  firebase_storage: ^11.4.1
  firebase_in_app_messaging: ^0.7.4+3
  email_validator: '^2.1.16'
  image_picker: '0.8.3'
  url_launcher: '^6.0.6'
  dio: '^5.4.0'
  file_picker: '6.1.1'
  path_provider: '2.0.15'
  lecle_downloads_path_provider: ^0.0.2+8
  cached_network_image: ^3.2.0
  firebase_app_check: ^0.2.1+6
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

#  fonts:
#    - family: SFPro-Semibold
#    - lib/view/fonts/FontsFree-Net-SFProText-Semibold.ttf
#
  assets:
    - lib/view/shared/assets/logounaerp.png
    - lib/view/shared/assets/gatobaiano.png



  uses-material-design: true

