// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcoWySwKpobpQT0slfug9e14MDv7nduWI',
    appId: '1:417871026107:web:d0dcb1928d9fdeb308169e',
    messagingSenderId: '417871026107',
    projectId: 'appnatacao',
    authDomain: 'appnatacao.firebaseapp.com',
    storageBucket: 'appnatacao.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIQHct2AHmpACBkwnNf0grn3ZNn6Oxt1E',
    appId: '1:417871026107:android:56612ce04b29cd6f08169e',
    messagingSenderId: '417871026107',
    projectId: 'appnatacao',
    storageBucket: 'appnatacao.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIn5cMdA9BaeDk3d9MKHes85jflxWM4Rk',
    appId: '1:417871026107:ios:b9ce04bc736f3f3108169e',
    messagingSenderId: '417871026107',
    projectId: 'appnatacao',
    storageBucket: 'appnatacao.appspot.com',
    iosBundleId: 'com.example.natacaoapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIn5cMdA9BaeDk3d9MKHes85jflxWM4Rk',
    appId: '1:417871026107:ios:0cb1ad5a27540dc708169e',
    messagingSenderId: '417871026107',
    projectId: 'appnatacao',
    storageBucket: 'appnatacao.appspot.com',
    iosBundleId: 'com.example.natacaoapp.RunnerTests',
  );
}
